// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: cart.proto

package cart

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralResponse) Reset() {
	*x = GeneralResponse{}
	mi := &file_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralResponse) ProtoMessage() {}

func (x *GeneralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralResponse.ProtoReflect.Descriptor instead.
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{0}
}

func (x *GeneralResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GeneralResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkuId         uint32                 `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartItemRequest) Reset() {
	*x = CreateCartItemRequest{}
	mi := &file_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartItemRequest) ProtoMessage() {}

func (x *CreateCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartItemRequest.ProtoReflect.Descriptor instead.
func (*CreateCartItemRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCartItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCartItemRequest) GetSkuId() uint32 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CreateCartItemRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RemoveCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkuId         uint32                 `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCartItemRequest) Reset() {
	*x = RemoveCartItemRequest{}
	mi := &file_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCartItemRequest) ProtoMessage() {}

func (x *RemoveCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCartItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveCartItemRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveCartItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveCartItemRequest) GetSkuId() uint32 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

type ClearCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartItemRequest) Reset() {
	*x = ClearCartItemRequest{}
	mi := &file_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartItemRequest) ProtoMessage() {}

func (x *ClearCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartItemRequest.ProtoReflect.Descriptor instead.
func (*ClearCartItemRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{3}
}

func (x *ClearCartItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListCartItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCartItemsRequest) Reset() {
	*x = ListCartItemsRequest{}
	mi := &file_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCartItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCartItemsRequest) ProtoMessage() {}

func (x *ListCartItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCartItemsRequest.ProtoReflect.Descriptor instead.
func (*ListCartItemsRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{4}
}

func (x *ListCartItemsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint32                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Price         uint32                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemResponse) Reset() {
	*x = CartItemResponse{}
	mi := &file_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemResponse) ProtoMessage() {}

func (x *CartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemResponse.ProtoReflect.Descriptor instead.
func (*CartItemResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{5}
}

func (x *CartItemResponse) GetSkuId() uint32 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CartItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartItemResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CartItemResponse) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ListCartItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItemResponse    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice    uint32                 `protobuf:"varint,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCartItemsResponse) Reset() {
	*x = ListCartItemsResponse{}
	mi := &file_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCartItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCartItemsResponse) ProtoMessage() {}

func (x *ListCartItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCartItemsResponse.ProtoReflect.Descriptor instead.
func (*ListCartItemsResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{6}
}

func (x *ListCartItemsResponse) GetItems() []*CartItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCartItemsResponse) GetTotalPrice() uint32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

var File_cart_proto protoreflect.FileDescriptor

const file_cart_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cart.proto\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\x0fGeneralResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x15CreateCartItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\rR\x05skuId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"G\n" +
	"\x15RemoveCartItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\rR\x05skuId\"/\n" +
	"\x14ClearCartItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"/\n" +
	"\x14ListCartItemsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"i\n" +
	"\x10CartItemResponse\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\rR\x05skuId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x14\n" +
	"\x05price\x18\x04 \x01(\rR\x05price\"a\n" +
	"\x15ListCartItemsResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.CartItemResponseR\x05items\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\rR\n" +
	"totalPrice2\xe5\x02\n" +
	"\vCartService\x12R\n" +
	"\vAddCartItem\x12\x16.CreateCartItemRequest\x1a\x10.GeneralResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/cart/item/add\x12X\n" +
	"\x0eDeleteCartItem\x12\x16.RemoveCartItemRequest\x1a\x10.GeneralResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/cart/item/delete\x12Q\n" +
	"\x0eClearCartItems\x12\x15.ClearCartItemRequest\x1a\x10.GeneralResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/cart/clear\x12U\n" +
	"\rListCartItems\x12\x15.ListCartItemsRequest\x1a\x16.ListCartItemsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/cart/listB\x18Z\x16cart/pkg/api/cart;cartb\x06proto3"

var (
	file_cart_proto_rawDescOnce sync.Once
	file_cart_proto_rawDescData []byte
)

func file_cart_proto_rawDescGZIP() []byte {
	file_cart_proto_rawDescOnce.Do(func() {
		file_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)))
	})
	return file_cart_proto_rawDescData
}

var file_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cart_proto_goTypes = []any{
	(*GeneralResponse)(nil),       // 0: GeneralResponse
	(*CreateCartItemRequest)(nil), // 1: CreateCartItemRequest
	(*RemoveCartItemRequest)(nil), // 2: RemoveCartItemRequest
	(*ClearCartItemRequest)(nil),  // 3: ClearCartItemRequest
	(*ListCartItemsRequest)(nil),  // 4: ListCartItemsRequest
	(*CartItemResponse)(nil),      // 5: CartItemResponse
	(*ListCartItemsResponse)(nil), // 6: ListCartItemsResponse
}
var file_cart_proto_depIdxs = []int32{
	5, // 0: ListCartItemsResponse.items:type_name -> CartItemResponse
	1, // 1: CartService.AddCartItem:input_type -> CreateCartItemRequest
	2, // 2: CartService.DeleteCartItem:input_type -> RemoveCartItemRequest
	3, // 3: CartService.ClearCartItems:input_type -> ClearCartItemRequest
	4, // 4: CartService.ListCartItems:input_type -> ListCartItemsRequest
	0, // 5: CartService.AddCartItem:output_type -> GeneralResponse
	0, // 6: CartService.DeleteCartItem:output_type -> GeneralResponse
	0, // 7: CartService.ClearCartItems:output_type -> GeneralResponse
	6, // 8: CartService.ListCartItems:output_type -> ListCartItemsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cart_proto_init() }
func file_cart_proto_init() {
	if File_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_proto_goTypes,
		DependencyIndexes: file_cart_proto_depIdxs,
		MessageInfos:      file_cart_proto_msgTypes,
	}.Build()
	File_cart_proto = out.File
	file_cart_proto_goTypes = nil
	file_cart_proto_depIdxs = nil
}
