// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: stocks.proto

package stocks

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneralResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralResponse) Reset() {
	*x = GeneralResponse{}
	mi := &file_stocks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralResponse) ProtoMessage() {}

func (x *GeneralResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralResponse.ProtoReflect.Descriptor instead.
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return file_stocks_proto_rawDescGZIP(), []int{0}
}

func (x *GeneralResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GeneralResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateStockItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkuId         uint32                 `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Price         uint32                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStockItemRequest) Reset() {
	*x = CreateStockItemRequest{}
	mi := &file_stocks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStockItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockItemRequest) ProtoMessage() {}

func (x *CreateStockItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockItemRequest.ProtoReflect.Descriptor instead.
func (*CreateStockItemRequest) Descriptor() ([]byte, []int) {
	return file_stocks_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStockItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateStockItemRequest) GetSkuId() uint32 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CreateStockItemRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CreateStockItemRequest) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateStockItemRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type DeleteStockItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkuId         uint32                 `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStockItemRequest) Reset() {
	*x = DeleteStockItemRequest{}
	mi := &file_stocks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStockItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStockItemRequest) ProtoMessage() {}

func (x *DeleteStockItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStockItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteStockItemRequest) Descriptor() ([]byte, []int) {
	return file_stocks_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteStockItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteStockItemRequest) GetSkuId() uint32 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

type GetStockItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint32                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockItemRequest) Reset() {
	*x = GetStockItemRequest{}
	mi := &file_stocks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockItemRequest) ProtoMessage() {}

func (x *GetStockItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockItemRequest.ProtoReflect.Descriptor instead.
func (*GetStockItemRequest) Descriptor() ([]byte, []int) {
	return file_stocks_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockItemRequest) GetSkuId() uint32 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

type FilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CurrentPage   int64                  `protobuf:"varint,4,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	mi := &file_stocks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_stocks_proto_rawDescGZIP(), []int{4}
}

func (x *FilterRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FilterRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *FilterRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FilterRequest) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

type StockItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         uint32                 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Count         uint32                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Price         uint32                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItemResponse) Reset() {
	*x = StockItemResponse{}
	mi := &file_stocks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItemResponse) ProtoMessage() {}

func (x *StockItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItemResponse.ProtoReflect.Descriptor instead.
func (*StockItemResponse) Descriptor() ([]byte, []int) {
	return file_stocks_proto_rawDescGZIP(), []int{5}
}

func (x *StockItemResponse) GetSkuId() uint32 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *StockItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockItemResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StockItemResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StockItemResponse) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StockItemResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ListStockItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItemResponse   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	PageNumber    int64                  `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStockItemsResponse) Reset() {
	*x = ListStockItemsResponse{}
	mi := &file_stocks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStockItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStockItemsResponse) ProtoMessage() {}

func (x *ListStockItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stocks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStockItemsResponse.ProtoReflect.Descriptor instead.
func (*ListStockItemsResponse) Descriptor() ([]byte, []int) {
	return file_stocks_proto_rawDescGZIP(), []int{6}
}

func (x *ListStockItemsResponse) GetItems() []*StockItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListStockItemsResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListStockItemsResponse) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

var File_stocks_proto protoreflect.FileDescriptor

const file_stocks_proto_rawDesc = "" +
	"\n" +
	"\fstocks.proto\x12\x06stocks\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\x0fGeneralResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x01\n" +
	"\x16CreateStockItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\rR\x05skuId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x14\n" +
	"\x05price\x18\x04 \x01(\rR\x05price\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\"H\n" +
	"\x16DeleteStockItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\rR\x05skuId\",\n" +
	"\x13GetStockItemRequest\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\rR\x05skuId\"\x84\x01\n" +
	"\rFilterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12!\n" +
	"\fcurrent_page\x18\x04 \x01(\x03R\vcurrentPage\"\x9a\x01\n" +
	"\x11StockItemResponse\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\rR\x05skuId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05count\x12\x14\n" +
	"\x05price\x18\x05 \x01(\rR\x05price\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\"\x89\x01\n" +
	"\x16ListStockItemsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.stocks.StockItemResponseR\x05items\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\rR\n" +
	"totalCount\x12\x1e\n" +
	"\n" +
	"pageNumber\x18\x03 \x01(\x03R\n" +
	"pageNumber2\xc0\x03\n" +
	"\rStocksService\x12d\n" +
	"\fAddStockItem\x12\x1e.stocks.CreateStockItemRequest\x1a\x17.stocks.GeneralResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/stocks/item/add\x12j\n" +
	"\x0fDeleteStockItem\x12\x1e.stocks.DeleteStockItemRequest\x1a\x17.stocks.GeneralResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/stocks/item/delete\x12h\n" +
	"\x11GetStockItemBySKU\x12\x1b.stocks.GetStockItemRequest\x1a\x19.stocks.StockItemResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/stocks/item/get\x12s\n" +
	"\x18ListStockItemsByLocation\x12\x15.stocks.FilterRequest\x1a\x1e.stocks.ListStockItemsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/stocks/list/locationB\x1eZ\x1cstocks/pkg/api/stocks;stocksb\x06proto3"

var (
	file_stocks_proto_rawDescOnce sync.Once
	file_stocks_proto_rawDescData []byte
)

func file_stocks_proto_rawDescGZIP() []byte {
	file_stocks_proto_rawDescOnce.Do(func() {
		file_stocks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stocks_proto_rawDesc), len(file_stocks_proto_rawDesc)))
	})
	return file_stocks_proto_rawDescData
}

var file_stocks_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stocks_proto_goTypes = []any{
	(*GeneralResponse)(nil),        // 0: stocks.GeneralResponse
	(*CreateStockItemRequest)(nil), // 1: stocks.CreateStockItemRequest
	(*DeleteStockItemRequest)(nil), // 2: stocks.DeleteStockItemRequest
	(*GetStockItemRequest)(nil),    // 3: stocks.GetStockItemRequest
	(*FilterRequest)(nil),          // 4: stocks.FilterRequest
	(*StockItemResponse)(nil),      // 5: stocks.StockItemResponse
	(*ListStockItemsResponse)(nil), // 6: stocks.ListStockItemsResponse
}
var file_stocks_proto_depIdxs = []int32{
	5, // 0: stocks.ListStockItemsResponse.items:type_name -> stocks.StockItemResponse
	1, // 1: stocks.StocksService.AddStockItem:input_type -> stocks.CreateStockItemRequest
	2, // 2: stocks.StocksService.DeleteStockItem:input_type -> stocks.DeleteStockItemRequest
	3, // 3: stocks.StocksService.GetStockItemBySKU:input_type -> stocks.GetStockItemRequest
	4, // 4: stocks.StocksService.ListStockItemsByLocation:input_type -> stocks.FilterRequest
	0, // 5: stocks.StocksService.AddStockItem:output_type -> stocks.GeneralResponse
	0, // 6: stocks.StocksService.DeleteStockItem:output_type -> stocks.GeneralResponse
	5, // 7: stocks.StocksService.GetStockItemBySKU:output_type -> stocks.StockItemResponse
	6, // 8: stocks.StocksService.ListStockItemsByLocation:output_type -> stocks.ListStockItemsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stocks_proto_init() }
func file_stocks_proto_init() {
	if File_stocks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stocks_proto_rawDesc), len(file_stocks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stocks_proto_goTypes,
		DependencyIndexes: file_stocks_proto_depIdxs,
		MessageInfos:      file_stocks_proto_msgTypes,
	}.Build()
	File_stocks_proto = out.File
	file_stocks_proto_goTypes = nil
	file_stocks_proto_depIdxs = nil
}
